name: Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  VITE_CLERK_PUBLISHABLE_KEY: pk_test_Y29taWMtc3F1aWQtODkuY2xlcmsuYWNjb3VudHMuZGV2JA
  CLERK_PUBLISHABLE_KEY: pk_test_Y29taWMtc3F1aWQtODkuY2xlcmsuYWNjb3VudHMuZGV2JA

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: frontend/node_modules
        key: ${{ runner.os }}-frontend-${{ hashFiles('frontend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-frontend-

          
    - name: Install dependencies
      run: |
        cd frontend
        npm ci

    - name: Build application
      run: |
        cd frontend
        npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: frontend/dist/

  test-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: frontend/node_modules
        key: ${{ runner.os }}-frontend-${{ hashFiles('frontend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-frontend-


    - name: Install dependencies
      run: |
        cd frontend
        npm i

    - name: Run tests
      run: |
        cd frontend
        npx vitest run --coverage

    - name: Upload artefacts
      uses: actions/upload-artifact@v3
      with:
        name: frontend-coverage
        path: frontend/coverage/
